story.setPagePauseLength(5000, 5000)
story.printText("This is a test of a really long piece of text that will likely wrap around in the screen.", 80, 60, 1, 15, story.TextSpeed.Normal)
scene.setBackgroundColor(11)
let textSprite = textsprite.create("And this is more text")
textSprite.setPosition(80, 60)
